### ISSUE TITLE
Tween Hardcore Tiles Upon Growth/Decay

### ISSUE THREAD

**Issue by a1theredbull** [Senior-Project-2013/Worphles#27]
Tween those things,
during growth and decay.

**Comment by a1theredbull** [comment]
It tweens,
will tween more efficiently later.

**Comment by calebgomer** [comment]
Can you close this issue and create one about improving efficiency?

**Comment by jordonbiondo** [comment]
WHAT IS TWEENING?

**Comment by calebgomer** [comment]
Try the latest version of the project, its awesome
